title: Mein Name
collections:
  index:
    output: true
    permalink: /_index/:path/
  projects:
    output: true
    permalink: /_projects/:path/
  drawings:
    output: true
    permalink: /_drawings/:path/
  archive:
    output: true
    permalink: /_archive/:path/
  about:
    output: true
    permalink: /_about/:path/
